# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ong
    name: somosmas
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    defer-datasource-initialization: false
    hibernate.ddl-auto: update

# Sendgrid
sendgrid:
  sender: foo
  key: foo

# AWS
aws:
  bucket-name: cohorte-junio-a192d78b
  public-key: foo
  secret-Key: foo
  region: us-east-1
