# Database
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/ong}
    name: ${DATABASE_NAME:somosmas}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: ${DATABASE_CLASS:com.mysql.jdbc.Driver}
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.MySQL5InnoDBDialect}
    show-sql: false
    defer-datasource-initialization: false
    hibernate.ddl-auto: update
  main:
    allow-circular-references: true

# Sendgrid
sendgrid:
  sender: ${SENDGRID_SENDER:foo@foo.com}
  key: ${SENDGRID_KEY:foo}

# AWS
aws:
  bucket-name: ${AWS_BUCKET:cohorte-junio-a192d78b}
  public-key: ${AWS_PUBLIC_KEY:foo}
  secret-key: ${AWS_SECRET_KEY:foo}
  region: ${AWS_REGION:us-east-1}